name: Docker Compose Deploy

on:
  push:
    branches:
      - main  # Replace with your target branch if needed

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
  setup-files:
    needs: checkout-code
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key and Known Hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          # Setup SSH directory
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
  deploy:
    needs: setup-files
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Docker Compose
        env:
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          HOST: ${{ secrets.HOST }}
        run: |
          sshpass -p $MY_PASSWORD $HOST << EOF
            cd project-cloudsystemen/  # Adjust the path
            git pull origin main  # Pull latest changes
            docker compose down  # Stop existing containers
            docker compose up -d  # Start updated containers
          EOF
